---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# - name: Install elasticsearch-curator dependencies
#   pip:
#     name: argparse

- name: Install elasticsearch-curator
  pip:
    name: elasticsearch-curator
    version: "{{ elasticsearch_curator_version }}"

- name: Create curator configuration directory
  file:
    dest: /etc/curator
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Deploy elasticsearch-curator configuration
  template:
    src: "{{ item }}.j2"
    dest: /etc/curator/{{ item }}
    mode: 0644
    owner: root
    group: root
  with_items:
    - config.yml
    - actions.yml
  notify: Run elasticsearch-curator

- name: Set cron path
  cron:
    name: PATH
    env: yes
    value: /usr/local/bin:/usr/bin
    user: {{ ansible_user_id }}
    cron_file: ansible_logstash-curator

- name: Configure cron jobs for Elasticsearch Curator.
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    minute: "{{ item.minute | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    day: "{{ item.day | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    month: "{{ item.month | default('*') }}"
    user: {{ ansible_user_id }}
    cron_file: ansible_logstash-curator
  with_items: "{{ elasticsearch_curator_cron_jobs }}"
